### PR TITLE
Grab bag of changes

### PR DESCRIPTION
**Pull request by indexzero**
@dtex did some long overdue maintenance. TravisCI should work now and I added you to all the necessary places (like file headers and `LICENSE`).

Apologies for the whitespace noise in this, but my editor settings have changed since it was written so it stripped all trailing space. While I generally am annoyed by this noise PRs it is for sure a best practice I should have had in the first place :smile_cat:

### CODE REVIEW

**Comment by dtex** [comment]
Oh man, thanks! I just figured out why the tests were never stopping and had been seeing the white space nags so no worries on that. Glad to have them gone.

I'll land this and soon as the tests are all green.

See you this weekend, I'm looking forward to your talk.

**Comment by dtex** [comment]
The failed checks might be the result of the thing I was talking about. I'll take a look.

**Comment by indexzero** [comment]
@dtex common failures. Fixed :+1: https://github.com/indexzero/neuron/commit/98cff621acb5a228d66b3ac7248f9a6f0586d66e

**Comment by dtex** [comment]
Thank you. 

Since I have your attention can I ask about something? On [this line](https://github.com/dtex/neuron/blob/master/lib/neuron/job-manager.js#L199) we are calling connect() on a cache that is already connected (on instantiation). Unless a user manually calls cache.close() the cache should already be open. 

The problem it causes is that the reference to the first connection is overwritten and cache.close() doesn't  close the first instance. The process never shuts down. If I just remove that line and call cache.close() at the right times, the test ends properly.

**Comment by indexzero** [comment]
> Since I have your attention can I ask about something? On this line we are calling connect() on a cache that is already connected (on instantiation). Unless a user manually calls cache.close() the cache should already be open.
> 
> The problem it causes is that the reference to the first connection is overwritten and cache.close() doesn't close the first instance. The process never shuts down. If I just remove that line and call cache.close() at the right times, the test ends properly.

Sounds like a bug :smile:

**Pull request merged**
